#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

OUTPUT=$(git status --porcelain)
if [ "$OUTPUT" != "" ]; then
    echo_error "git repo not clean, please commit everything"
    git status
    exit 1
fi

echo_info "Building..."
s/build

echo_info "Deploying..."
rsync -azvh --delete dist/ abstract.properties:/srv/www/shareshare.abstract.properties

echo_good "All done!"
